# Generated by Django 5.0.6 on 2024-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messanger',
            name='update_status',
            field=models.CharField(default='', max_length=9),
        ),
    ]
