# Generated by Django 5.0.6 on 2024-05-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_messanger_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messanger',
            name='author_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
