# Generated by Django 5.0.6 on 2024-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
