# Generated by Django 5.0.6 on 2024-05-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_task',
            field=models.CharField(default='', max_length=9),
        ),
    ]
